/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.util.Scanner;
import javax.swing.*;
import jogo.Jogador;

/**
 *
 * @author braya
 */
public class Jogo extends javax.swing.JFrame {

    /**
     * Creates new form Jogo
     */
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_boneco = new javax.swing.JLabel();
        lbl_telanvl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 51, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1200, 720));
        getContentPane().setLayout(null);

        lbl_boneco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Prancheta 1.png"))); // NOI18N
        lbl_boneco.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbl_bonecoMouseMoved(evt);
            }
        });
        lbl_boneco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbl_bonecoMouseReleased(evt);
            }
        });
        lbl_boneco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lbl_bonecoKeyReleased(evt);
            }
        });
        getContentPane().add(lbl_boneco);
        lbl_boneco.setBounds(20, 590, 60, 70);

        lbl_telanvl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Prancheta 1_1.png"))); // NOI18N
        lbl_telanvl1.setAlignmentY(0.0F);
        lbl_telanvl1.setAutoscrolls(true);
        lbl_telanvl1.setPreferredSize(new java.awt.Dimension(1820, 920));
        lbl_telanvl1.setRequestFocusEnabled(false);
        getContentPane().add(lbl_telanvl1);
        lbl_telanvl1.setBounds(0, 0, 1200, 720);
        lbl_telanvl1.getAccessibleContext().setAccessibleName("cenarioJogo1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_bonecoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bonecoMouseReleased
        // TODO add your handling code here:
        System.out.println("a"); ///ação ocorre quando clica encima
    }//GEN-LAST:event_lbl_bonecoMouseReleased

    private void lbl_bonecoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_bonecoMouseMoved
        // O add your handling code here:
        System.out.println("b");//ativa o comando quando o mouse fica encima
    }//GEN-LAST:event_lbl_bonecoMouseMoved

    private void lbl_bonecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbl_bonecoKeyReleased
        // TODO add your handling code here:
        Scanner sc = new Scanner(System.in);
        String key = sc.next();
        switch (key) {
            case "d": 
                
                break;
            default:
                throw new AssertionError();
        }
        
    }//GEN-LAST:event_lbl_bonecoKeyReleased

    /**
     * @param args the command line arguments
     */

    
    
    
    
    
    
    
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jogo().setVisible(true);
            }
        });
    }
      /*public Jogo() {
        initComponents();
        setResizable(true);
          setTitle("Jogo");
          setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
          setLayout(new BorderLayout());
          JButton botao = new JButton("expandir a tela");
          add(botao, BorderLayout.CENTER);
          setVisible(true);
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_boneco;
    private javax.swing.JLabel lbl_telanvl1;
    // End of variables declaration//GEN-END:variables
}
