/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

/**
 *
 * @author braya
 */
public class Cadastrar extends javax.swing.JFrame {

    private String username;
    private String gmail;
    private String senha;
    private String rpsenha;

    /**
     * Creates new form Login
     */
    public Cadastrar() {

        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_comando_2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_senha = new javax.swing.JTextField();
        lbl_senha = new javax.swing.JLabel();
        txt_senha_repetir = new javax.swing.JTextField();
        lbl_senha_repetir = new javax.swing.JLabel();
        bt_criar_conta = new javax.swing.JButton();
        lbl_fundo_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_comando_2.setBackground(new java.awt.Color(0, 0, 0));
        lbl_comando_2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_comando_2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_comando_2.setText("Complete suas informações para criar uma conta");
        getContentPane().add(lbl_comando_2);
        lbl_comando_2.setBounds(210, 60, 830, 60);

        txt_username.setBackground(new java.awt.Color(255, 255, 255));
        txt_username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_username.setName(""); // NOI18N
        getContentPane().add(txt_username);
        txt_username.setBounds(580, 210, 300, 30);

        lbl_username.setBackground(new java.awt.Color(255, 255, 255));
        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(0, 0, 0));
        lbl_username.setText("Username");
        lbl_username.setOpaque(true);
        getContentPane().add(lbl_username);
        lbl_username.setBounds(400, 210, 480, 30);
        lbl_username.getAccessibleContext().setAccessibleDescription("");

        txt_email.setBackground(new java.awt.Color(255, 255, 255));
        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_email);
        txt_email.setBounds(580, 250, 300, 30);

        lbl_email.setBackground(new java.awt.Color(255, 255, 255));
        lbl_email.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_email.setForeground(new java.awt.Color(0, 0, 0));
        lbl_email.setText("Email");
        lbl_email.setOpaque(true);
        getContentPane().add(lbl_email);
        lbl_email.setBounds(400, 250, 480, 30);

        txt_senha.setBackground(new java.awt.Color(255, 255, 255));
        txt_senha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_senha);
        txt_senha.setBounds(580, 290, 300, 30);

        lbl_senha.setBackground(new java.awt.Color(255, 255, 255));
        lbl_senha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_senha.setForeground(new java.awt.Color(0, 0, 0));
        lbl_senha.setText("Senha");
        lbl_senha.setOpaque(true);
        getContentPane().add(lbl_senha);
        lbl_senha.setBounds(400, 290, 480, 30);

        txt_senha_repetir.setBackground(new java.awt.Color(255, 255, 255));
        txt_senha_repetir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_senha_repetir);
        txt_senha_repetir.setBounds(580, 330, 300, 30);

        lbl_senha_repetir.setBackground(new java.awt.Color(255, 255, 255));
        lbl_senha_repetir.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_senha_repetir.setForeground(new java.awt.Color(0, 0, 0));
        lbl_senha_repetir.setText("Repita senha");
        lbl_senha_repetir.setOpaque(true);
        getContentPane().add(lbl_senha_repetir);
        lbl_senha_repetir.setBounds(400, 330, 480, 30);

        bt_criar_conta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bt_criar_conta.setText("Criar conta");
        bt_criar_conta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_criar_contaMouseClicked(evt);
            }
        });
        getContentPane().add(bt_criar_conta);
        bt_criar_conta.setBounds(560, 410, 160, 50);

        lbl_fundo_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo_container_img.png"))); // NOI18N
        getContentPane().add(lbl_fundo_login);
        lbl_fundo_login.setBounds(0, 0, 1280, 720);
        lbl_fundo_login.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_criar_contaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_criar_contaMouseClicked
        username = txt_username.getText();
        gmail = txt_username.getText();
        senha = txt_senha.getText();
        rpsenha = txt_senha_repetir.getText();
        //////////adicionar banco de dados
        ///
       /*
       cadastrar conta ao banco de dados
  
        avisar para entrar apos criar conta
        */
        
        
        

        // TODO add your handling code here:
        System.out.println("Cadastrado");
    }//GEN-LAST:event_bt_criar_contaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_criar_conta;
    private javax.swing.JLabel lbl_comando_2;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_fundo_login;
    private javax.swing.JLabel lbl_senha;
    private javax.swing.JLabel lbl_senha_repetir;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_senha;
    private javax.swing.JTextField txt_senha_repetir;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
