/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import javax.swing.JTextField;
import niveis.SelecionarNiveis;

/**
 *
 * @author braya
 */
public class Entrar extends javax.swing.JFrame {

    String nome;
    String senha;

    /**
     * Creates new form Entrar
     */
    public Entrar() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username_entrar = new javax.swing.JTextField();
        txt_senha_entrar = new javax.swing.JTextField();
        lbl_username_entrar = new javax.swing.JLabel();
        lbl_senha_entrar = new javax.swing.JLabel();
        bt_entrar = new javax.swing.JButton();
        lbl_comando_2_entrar = new javax.swing.JLabel();
        lbl_fundo_login = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1820, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        txt_username_entrar.setBackground(new java.awt.Color(255, 255, 255));
        txt_username_entrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txt_username_entrar.setName(""); // NOI18N
        getContentPane().add(txt_username_entrar);
        txt_username_entrar.setBounds(580, 210, 300, 30);

        txt_senha_entrar.setBackground(new java.awt.Color(255, 255, 255));
        txt_senha_entrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(txt_senha_entrar);
        txt_senha_entrar.setBounds(580, 250, 300, 30);

        lbl_username_entrar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_username_entrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_username_entrar.setForeground(new java.awt.Color(0, 0, 0));
        lbl_username_entrar.setText("Username");
        lbl_username_entrar.setOpaque(true);
        getContentPane().add(lbl_username_entrar);
        lbl_username_entrar.setBounds(400, 210, 480, 30);

        lbl_senha_entrar.setBackground(new java.awt.Color(255, 255, 255));
        lbl_senha_entrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_senha_entrar.setForeground(new java.awt.Color(0, 0, 0));
        lbl_senha_entrar.setText("Senha");
        lbl_senha_entrar.setOpaque(true);
        getContentPane().add(lbl_senha_entrar);
        lbl_senha_entrar.setBounds(400, 250, 480, 30);

        bt_entrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bt_entrar.setForeground(new java.awt.Color(0, 0, 0));
        bt_entrar.setText("Entrar");
        bt_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_entrarMouseClicked(evt);
            }
        });
        getContentPane().add(bt_entrar);
        bt_entrar.setBounds(560, 410, 160, 50);

        lbl_comando_2_entrar.setBackground(new java.awt.Color(0, 0, 0));
        lbl_comando_2_entrar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_comando_2_entrar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_comando_2_entrar.setText("Complete suas informações para entrar");
        getContentPane().add(lbl_comando_2_entrar);
        lbl_comando_2_entrar.setBounds(300, 60, 670, 60);

        lbl_fundo_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo_container_img.png"))); // NOI18N
        getContentPane().add(lbl_fundo_login);
        lbl_fundo_login.setBounds(0, 0, 1280, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entrarMouseClicked
      

        nome = txt_username_entrar.getText();
        senha = txt_senha_entrar.getText();
        /////adicionar banco de dados
        /*
        if(nome == bancodedados){
        acosso permetido
        }else{
        acesso negado por falta de dados
        }
        */
        
        setVisible(false);
        new SelecionarNiveis().setVisible(true);
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_entrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrar().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_entrar;
    private javax.swing.JLabel lbl_comando_2_entrar;
    private javax.swing.JLabel lbl_fundo_login;
    private javax.swing.JLabel lbl_senha_entrar;
    private javax.swing.JLabel lbl_username_entrar;
    private javax.swing.JTextField txt_senha_entrar;
    private javax.swing.JTextField txt_username_entrar;
    // End of variables declaration//GEN-END:variables
}
