/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
import login.*;

/**
 *
 * @author braya
 */
public class Tela_1 extends javax.swing.JFrame {

    /**
     * Creates new form Tela_1
     */
    int click_tela_1 = 0;
    

    public Tela_1() {

        System.out.println(click_tela_1);
        initComponents();
        bt_cadastrarse.setVisible(false);
        bt_entrar.setVisible(false);
        
        addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {


            }
        });
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_comando_1 = new javax.swing.JLabel();
        lbl_mensagem_1 = new javax.swing.JLabel();
        bt_cadastrarse = new javax.swing.JButton();
        bt_entrar = new javax.swing.JButton();
        lbl_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_comando_1.setBackground(new java.awt.Color(102, 0, 0));
        lbl_comando_1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_comando_1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_comando_1.setText("Clique na tela");
        getContentPane().add(lbl_comando_1);
        lbl_comando_1.setBounds(560, 300, 160, 70);

        lbl_mensagem_1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_mensagem_1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_mensagem_1.setText("Bem-Vindo");
        getContentPane().add(lbl_mensagem_1);
        lbl_mensagem_1.setBounds(510, 180, 260, 80);

        bt_cadastrarse.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bt_cadastrarse.setText("Cadastrar-se");
        bt_cadastrarse.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_cadastrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_cadastrarseMouseClicked(evt);
            }
        });
        getContentPane().add(bt_cadastrarse);
        bt_cadastrarse.setBounds(540, 350, 200, 40);

        bt_entrar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bt_entrar.setText("Entrar");
        bt_entrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_entrarMouseClicked(evt);
            }
        });
        getContentPane().add(bt_entrar);
        bt_entrar.setBounds(540, 290, 200, 40);

        lbl_fundo.setBackground(new java.awt.Color(204, 0, 0));
        lbl_fundo.setForeground(new java.awt.Color(204, 0, 0));
        lbl_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo_container_img.png"))); // NOI18N
        lbl_fundo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_fundoMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_fundo);
        lbl_fundo.setBounds(0, 0, 1280, 720);
        lbl_fundo.getAccessibleContext().setAccessibleName("lbl_fundo_container");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_fundoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_fundoMouseClicked
        System.out.println("fundo clicado");
                        if (click_tela_1 ==0) {
                    setVisible(true);
                    lbl_mensagem_1.setVisible(false);
                    lbl_comando_1.setVisible(false);
                    bt_entrar.setVisible(true);
                    bt_cadastrarse.setVisible(true);
                } else if(click_tela_1!=1) {
                    setVisible(false);
                    new Cadastrar().setVisible(true);
                    lbl_mensagem_1.setVisible(true);
                    lbl_comando_1.setVisible(true);
                    bt_entrar.setVisible(false);
                    bt_cadastrarse.setVisible(false);
                }

        
        
        
    }//GEN-LAST:event_lbl_fundoMouseClicked

    private void bt_entrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_entrarMouseClicked
        System.out.println("botao entrar");
        setVisible(false);
        new Entrar().setVisible(true);
        

        

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_entrarMouseClicked

    private void bt_cadastrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_cadastrarseMouseClicked
        System.out.println("botao cadastrara");
        setVisible(false);
        new Cadastrar().setVisible(true);
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_bt_cadastrarseMouseClicked

    /* @param args the command line arguments*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Tela_1().setVisible(true);

            }
        });

        // new Tela_1().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrarse;
    private javax.swing.JButton bt_entrar;
    private javax.swing.JLabel lbl_comando_1;
    private javax.swing.JLabel lbl_fundo;
    private javax.swing.JLabel lbl_mensagem_1;
    // End of variables declaration//GEN-END:variables

}
