/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package niveis;

/**
 *
 * @author braya
 */
public class SelecionarNiveis extends javax.swing.JFrame {

    /**
     * Creates new form SelecionarNiveis
     */
    public SelecionarNiveis() {
        initComponents();
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nvl_4 = new javax.swing.JLabel();
        lbl_nvl_1 = new javax.swing.JLabel();
        lbl_nvl_5 = new javax.swing.JLabel();
        lbl_nvl_7 = new javax.swing.JLabel();
        lbl_nvl_8 = new javax.swing.JLabel();
        lbl_nvl_3 = new javax.swing.JLabel();
        lbl_nvl_6 = new javax.swing.JLabel();
        lbl_nvl_9 = new javax.swing.JLabel();
        lbl_nvl_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        lbl_nvl_4.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_4.setOpaque(true);
        getContentPane().add(lbl_nvl_4);
        lbl_nvl_4.setBounds(230, 250, 250, 150);

        lbl_nvl_1.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_1.setOpaque(true);
        lbl_nvl_1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbl_nvl_1);
        lbl_nvl_1.setBounds(230, 50, 250, 150);

        lbl_nvl_5.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_5.setOpaque(true);
        getContentPane().add(lbl_nvl_5);
        lbl_nvl_5.setBounds(530, 250, 250, 150);

        lbl_nvl_7.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_7.setOpaque(true);
        getContentPane().add(lbl_nvl_7);
        lbl_nvl_7.setBounds(230, 450, 250, 150);

        lbl_nvl_8.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_8.setOpaque(true);
        getContentPane().add(lbl_nvl_8);
        lbl_nvl_8.setBounds(530, 450, 250, 150);

        lbl_nvl_3.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_3.setOpaque(true);
        getContentPane().add(lbl_nvl_3);
        lbl_nvl_3.setBounds(830, 50, 250, 150);

        lbl_nvl_6.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_6.setOpaque(true);
        getContentPane().add(lbl_nvl_6);
        lbl_nvl_6.setBounds(830, 250, 250, 150);

        lbl_nvl_9.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_9.setOpaque(true);
        getContentPane().add(lbl_nvl_9);
        lbl_nvl_9.setBounds(830, 450, 250, 150);

        lbl_nvl_2.setBackground(new java.awt.Color(204, 204, 204));
        lbl_nvl_2.setOpaque(true);
        getContentPane().add(lbl_nvl_2);
        lbl_nvl_2.setBounds(530, 50, 250, 150);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionarNiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionarNiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionarNiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionarNiveis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelecionarNiveis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_nvl_1;
    private javax.swing.JLabel lbl_nvl_2;
    private javax.swing.JLabel lbl_nvl_3;
    private javax.swing.JLabel lbl_nvl_4;
    private javax.swing.JLabel lbl_nvl_5;
    private javax.swing.JLabel lbl_nvl_6;
    private javax.swing.JLabel lbl_nvl_7;
    private javax.swing.JLabel lbl_nvl_8;
    private javax.swing.JLabel lbl_nvl_9;
    // End of variables declaration//GEN-END:variables
}
